
spring:
  application:
    name: gym-management
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gym?
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    #    配置redis
    redis:
      host: localhost
      port: 6379


mybatis-plus:     #直接配置mybatisplus，不会影响mybatis的使用
  type-aliases-package: com.bequre.pojo
  #  mapper-locations:  #这个其实都不用配，有默认
  global-config:
    db-config:
      id-type: auto   #默认的主键id策略
  configuration:
    map-underscore-to-camel-case: true    #开启驼峰命名转换

# 接口文档
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '管理端API'
      paths-to-match: '/**'
      packages-to-scan: com.bequre.controller   # 扫描的包，注意改成自己的包

